#ifndef AUTOMATED_WAREHOUSE_DYNAMIC_WAREHOUSE_DESIGNER_H
#define AUTOMATED_WAREHOUSE_DYNAMIC_WAREHOUSE_DESIGNER_H

#include <stdio.h>

int dynamicWarehouseDesign();

#endif //AUTOMATED_WAREHOUSE_DYNAMIC_WAREHOUSE_DESIGNER_H
